/*
  AIfES MNIST FNN (f32) - 784 -> 128(ReLU) -> 64(ReLU) -> 10(Softmax)
  Generated by AIfES-Converter (keras2aifes.convert_to_fnn_f32), adapted for bare-metal STM32:
    - aifes_f32_fnn_inference() takes explicit input/output shapes (as used by aifes_app.c)
    - inference workspace is a static buffer (no malloc, no heap needed)
    - printing goes through the AIPRINT* macros (no-ops when AIDEBUG_ENABLE_PRINTING is off)
    - Dense layers use CMSIS if AIFES_WITH_CMSIS is defined in aifes_config.h (Cortex-M only)

  Original: Copyright (C) 2022 Fraunhofer Institute for Microelectronic Circuits and Systems.
  AIfES-Converter is free software under the GNU AGPL v3 or later.
*/

#ifndef AIFES_F32_FNN
#define AIFES_F32_FNN

#include <stdint.h>
#include <stddef.h>
#include <aifes.h>
#include "aifes_f32_weights.h"      /* const float aifes_f32_flat_weights[] */
#if defined(AIFES_WITH_CMSIS) && __arm__
#include <aifes_cmsis.h>
#define AIFES_DENSE(layer, prev)  ailayer_dense_f32_cmsis(layer, prev)
#else
#define AIFES_DENSE(layer, prev)  ailayer_dense_f32_default(layer, prev)
#endif

#define DATASETS 1
#define INPUTS   784
#define OUTPUTS  10

/* Static inference workspace; the needed size is checked at run time (create_model() returns 1 if too small). */
#ifndef AIFES_INFERENCE_MEM_BYTES
#define AIFES_INFERENCE_MEM_BYTES  (8 * 1024)   /* model needs 6272 B */
#endif
static uint8_t aifes_inference_memory[AIFES_INFERENCE_MEM_BYTES] __attribute__((aligned(8)));

aimodel_t model;

/* Layer definition */
uint16_t input_layer_shape[] = {DATASETS, INPUTS};

ailayer_input_f32_t   input_layer     = AILAYER_INPUT_F32_A(2, input_layer_shape);
ailayer_dense_f32_t   dense_layer_1   = AILAYER_DENSE_F32_A(128);
ailayer_relu_f32_t    relu_layer_1    = AILAYER_RELU_F32_A();
ailayer_dense_f32_t   dense_layer_2   = AILAYER_DENSE_F32_A(64);
ailayer_relu_f32_t    relu_layer_2    = AILAYER_RELU_F32_A();
ailayer_dense_f32_t   dense_layer_3   = AILAYER_DENSE_F32_A(10);
ailayer_softmax_f32_t softmax_layer_3 = AILAYER_SOFTMAX_F32_A();

/* Returns 0 on success, 1 on failure (parameter/workspace size mismatch). */
uint8_t aifes_f32_fnn_create_model(void)
{
  ailayer_t *x;

  model.input_layer = ailayer_input_f32_default(&input_layer);
  x = AIFES_DENSE(&dense_layer_1, model.input_layer);
  x = ailayer_relu_f32_default(&relu_layer_1, x);
  x = AIFES_DENSE(&dense_layer_2, x);
  x = ailayer_relu_f32_default(&relu_layer_2, x);
  x = AIFES_DENSE(&dense_layer_3, x);
  x = ailayer_softmax_f32_default(&softmax_layer_3, x);
  model.output_layer = x;

  aialgo_compile_model(&model);

  /* Weights stay in flash (const); AIfES only reads them. */
  uint32_t parameter_memory_size = aialgo_sizeof_parameter_memory(&model);
  if (parameter_memory_size > sizeof(aifes_f32_flat_weights))
  {
    AIPRINT("Weights array is smaller than the model needs.\n");
    return 1;
  }
  aialgo_distribute_parameter_memory(&model, (void *) aifes_f32_flat_weights, parameter_memory_size);

  uint32_t memory_size = aialgo_sizeof_inference_memory(&model);
  AIPRINT("AIfES inference memory (bytes): ");
  AIPRINT_UINT("%u", (unsigned int) memory_size);
  AIPRINT("\n");
  if (memory_size > sizeof(aifes_inference_memory))
  {
    AIPRINT("AIFES_INFERENCE_MEM_BYTES too small.\n");
    return 1;
  }

  aialgo_schedule_inference_memory(&model, aifes_inference_memory, memory_size);
  return 0;
}

/* in_shape = {1, 784}, out_shape = {1, 10}; both arrays must stay valid during the call. */
void aifes_f32_fnn_inference(float *input_data, uint16_t *in_shape,
                             float *output_data, uint16_t *out_shape)
{
  aitensor_t input_tensor  = AITENSOR_2D_F32(in_shape, input_data);
  aitensor_t output_tensor = AITENSOR_2D_F32(out_shape, output_data);

  aialgo_inference_model(&model, &input_tensor, &output_tensor);
}

#endif /* AIFES_F32_FNN */
